name: Test and coverage

on: [push, pull_request]

jobs:
  check:
    name: Check
    strategy:
      matrix:
        go-version: [1.18.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Vet check
        run: go vet -v

      - name: Run coverage
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic -failfast

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
